
version: "3.9"

services:
  messaging_app:
    build:
      context: ./                # outer folder
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./messaging_app:/app/messaging_app   # live code reload
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: