apiVersion: apps/v1  # Kubernetes API version we are using
kind: Deployment      # Tells Kubernetes we are defining a deployment
metadata:
  name: messaging-app-deployment  # Name of this deployment object
  labels:                        # Tags used for grouping/filtering
    app: messaging_app
spec:                            # Desired state of this deployment
  replicas: 3                    # Run 3 pods
  selector:
    matchLabels:                 # Tells deployment which pods it manages
      app: messaging_app
  template:                      # Blueprint for pods
    metadata:
      labels:
        app: messaging_app       # How deployment finds its pods
    spec:                        # What is inside the pod
      containers:
      - name: messaging-app
        image: alx-backend-python-messaging_app:2.0
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "messaging_app.settings"
