pipeline {
    agent any

    environment {
        // Use your Jenkins credential ID for GitHub
        GIT_CREDENTIALS_ID = '1234'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: "${env.GIT_CREDENTIALS_ID}",
                    url: 'https://github.com/Amandecoe/alx-backend-python/messaging_app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh '''
                    . venv/bin/activate
                    pytest --junitxml=reports/test-results.xml
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/reports/test-results.xml'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished!'
        }
    }
}
