#!/bin/bash

echo "======= Kubernetes Setup Script ========="
#Number one, Check if Minikube is installed
if ! command -v minikube &> /dev/null
then
    echo "Minikube not found. Installing...."
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube
    echo "Minikube installed"
else
    echo "Minikube is already installed."
fi

#Number two, Start minikube with Docker Driver
echo "starting Minikube cluster..."
minikube start --driver=docker

#Number three, verify the cluster is running
kubectl cluster-info

#Number four, Retrieve the available pods
echo "Listing all pods in all namespaces"
kubectl get pods -A
