name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install django mysqlclient flake8 coverage

      # 4️⃣ Run flake8 linting
      - name: Lint with flake8
        run: |
          . venv/bin/activate
          cd messaging_app
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      # 5️⃣ Run Django tests with coverage
      - name: Run tests with coverage
        run: |
          . venv/bin/activate
          cd messaging_app
          coverage run --source='.' manage.py test chats
          coverage xml
          coverage html

      # 6️⃣ Upload coverage reports as artifacts
      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            messaging_app/coverage.xml
            messaging_app/htmlcov/