name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.amanuelpk }}
          password: ${{ secrets.dckr_pat_tTrlhDDr-4gk8iBuovUPGCuLdLI }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          cd messaging_app               # inner project folder
          docker build -t ${{ secrets.amanuelpk }}/messaging_app:latest .

      # 4️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.amanuelpk }}/messaging_app:latest