# Generated by Django 5.2.5 on 2025-08-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
