# Generated by Django 5.2.5 on 2025-08-21 09:04

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_user_password_hash_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-21 10:00:00', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participants_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
