# Generated by Django 5.2.5 on 2025-08-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_user_created_at_alter_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
