# Generated by Django 5.2.5 on 2025-08-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participants_id',
            new_name='participants',
        ),
    ]
